### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by MatthewScholefield** [LucaCappelletti94/support_developer#1]
Hi there, cool project! Heads up, this doesn't seem to have a license. I noticed this when auditing the dependencies of `silence_tensorflow` when determining whether to use the library. Would be nice to add MIT.

**Comment by LucaCappelletti94** [comment]
Sure, happy to add MIT. I just remembered about this one because, as you can see [here on Pepy](https://pepy.tech/project/support-developer), this package is being downloaded about 10000 times per week as a dependency of my many open-source. Yet, only one person decided to support my work with 1 euro per month :p 

The idea has not worked well — a sad statement on the open-source community.

**Comment by LucaCappelletti94** [comment]
Added license.
